"""
bootstrap.py — Building the shell script that configures a server.

The output is a single self-contained bash script. It is idempotent: running it
twice changes nothing the second time, which matters because "deploy" is what
you do every time you add a peer.

Config payloads are base64-encoded into shell variables rather than written as
heredocs. Heredocs would be read from the same stdin stream the script itself
arrives on when it is piped to `bash -s`, and any quoting character inside a
key would need escaping. Base64 sidesteps both problems — its alphabet cannot
contain a quote, so the payloads can be single-quoted without escaping at all.

Two targets:
  linux_bootstrap  Debian/Ubuntu, incl. Raspberry Pi OS — used for remote VPS
                   deployments and for native installs on a Linux box.
  macos_bootstrap  Native install on macOS via Homebrew and pf.
"""

from __future__ import annotations

import base64
import ipaddress
from pathlib import Path

from . import obfuscation, render
from .model import Site

NAT_HELPER_PATH = "/usr/local/sbin/vpn-agent-nat"
NAT_UNIT_PATH = "/etc/systemd/system/vpn-agent-nat.service"
SYSCTL_PATH = "/etc/sysctl.d/99-vpn-agent.conf"
PF_ANCHOR_PATH = "/etc/pf.anchors/vpn-agent"
PF_MARKER = "# >>> vpn-agent >>>"

# The teardown's pf surgery: print every line except our marker block, so
# Apple's own anchors in the same /etc/pf.conf survive untouched. Kept as a
# named constant so a test can run the exact program that ships in the script
# (see tests/test_v2_hardening.py::test_native_teardown_awk_*).
PF_STRIP_AWK = (
    "/vpn-agent >>>/ { skip = 1 } skip == 0 { print } /vpn-agent <<</ { skip = 0 }"
)


def _b64(text: str) -> str:
    return base64.standard_b64encode(text.encode("utf-8")).decode("ascii")


# ── Linux ────────────────────────────────────────


def linux_bootstrap(site: Site) -> str:
    """Render the Debian/Ubuntu install script for a site."""
    wg_conf = render.wg_server_config(site)
    subnets4 = " ".join(site.natted_subnets())
    subnet6 = site.wg_subnet6 if site.enable_ipv6 else ""

    parts: list[str] = [
        _linux_preamble(site),
        _linux_packages(site),
        _linux_write_wireguard(site, wg_conf),
    ]

    if site.enable_openvpn:
        parts.append(_linux_write_openvpn(site))

    parts += [
        _linux_forwarding(site),
        _linux_nat(site, subnets4, subnet6),
        _linux_firewall(site),
        _linux_services(site),
    ]

    # After the services, so OpenVPN is already listening on loopback by the
    # time stunnel is pointed at it and the onion service is published.
    parts.append(obfuscation.linux_stunnel_section(site))
    parts.append(obfuscation.linux_onion_section(site))

    parts.append(_linux_verify(site))
    return "\n".join(part for part in parts if part)


def _linux_preamble(site: Site) -> str:
    return f"""#!/usr/bin/env bash
#
# {site.name} — VPN server bootstrap (Debian/Ubuntu)
# Generated by VPN Agent. Idempotent: safe to re-run on every deploy.
#
# Contains private keys. It is streamed over SSH and never written to disk on
# the target.

set -euo pipefail
umask 077

# A note on why nothing below is written as `producer | grep -q pattern`:
#
# grep -q exits the moment it matches. That closes the pipe, the producer gets
# SIGPIPE and dies with status 141, and `set -o pipefail` reports 141 for the
# whole pipeline — so the test reads as FALSE exactly when the pattern WAS
# found. It only bites when the producer is still writing as grep exits, which
# is why a short producer looks fine and `systemctl list-unit-files` does not.
#
# Every test here captures output into a variable first and matches with `case`.

log()  {{ printf '\\033[36m[vpn-agent]\\033[0m %s\\n' "$*"; }}
warn() {{ printf '\\033[33m[vpn-agent] WARN:\\033[0m %s\\n' "$*" >&2; }}
die()  {{ printf '\\033[31m[vpn-agent] ERROR:\\033[0m %s\\n' "$*" >&2; exit 1; }}

[ "$(id -u)" -eq 0 ] || die "This script must run as root (use sudo)."

# BSD and GNU base64 disagree on the decode flag; pick whichever this host has.
if printf 'dGVzdA==' | base64 --decode >/dev/null 2>&1; then
    B64D="base64 --decode"
else
    B64D="base64 -D"
fi

write_file() {{
    # write_file <dest> <mode> <base64-content>
    local dest="$1" mode="$2" payload="$3"
    mkdir -p "$(dirname "$dest")"
    printf '%s' "$payload" | $B64D > "$dest.tmp"
    chmod "$mode" "$dest.tmp"
    mv -f "$dest.tmp" "$dest"
}}

if ! command -v apt-get >/dev/null 2>&1; then
    die "No apt-get found. This installer targets Debian, Ubuntu and Raspberry Pi OS."
fi

log "Configuring {site.name} ({site.mode} mode)"
"""


def _linux_packages(site: Site) -> str:
    packages = ["wireguard", "wireguard-tools", "iptables"]
    if site.enable_openvpn:
        packages.append("openvpn")
    package_list = " ".join(packages)

    return f"""
# ── Packages ────────────────────────────────────
missing=""
for pkg in {package_list}; do
    status="$(dpkg-query -W -f='${{Status}}' "$pkg" 2>/dev/null || true)"
    case "$status" in
        "install ok installed") ;;
        *) missing="$missing $pkg" ;;
    esac
done

if [ -n "$missing" ]; then
    log "Installing:$missing"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq $missing
else
    log "All packages already present."
fi
"""


def _linux_write_wireguard(site: Site, wg_conf: str) -> str:
    return f"""
# ── WireGuard config ────────────────────────────
WG_CONF_B64='{_b64(wg_conf)}'
write_file /etc/wireguard/{site.wg_interface}.conf 600 "$WG_CONF_B64"
log "Wrote /etc/wireguard/{site.wg_interface}.conf ({len([p for p in site.peers if p.enabled])} peer(s))"
"""


def _linux_write_openvpn(site: Site) -> str:
    ovpn_conf = render.ovpn_server_config(site)
    return f"""
# ── OpenVPN config ──────────────────────────────
OVPN_CONF_B64='{_b64(ovpn_conf)}'
OVPN_CA_B64='{_b64(site.ca_cert_pem)}'
OVPN_CERT_B64='{_b64(site.server_cert_pem)}'
OVPN_KEY_B64='{_b64(site.server_key_pem)}'
OVPN_TLSCRYPT_B64='{_b64(site.tls_crypt_key)}'

mkdir -p /etc/openvpn/server /var/log/openvpn
chmod 700 /etc/openvpn/server

# OpenVPN drops to nobody after start-up but keeps rewriting the status file.
# Left root-owned, the reopen after a SIGUSR1 restart fails and the daemon dies.
chown nobody:nogroup /var/log/openvpn 2>/dev/null || true

write_file /etc/openvpn/server/server.conf   644 "$OVPN_CONF_B64"
write_file /etc/openvpn/server/ca.crt        644 "$OVPN_CA_B64"
write_file /etc/openvpn/server/server.crt    644 "$OVPN_CERT_B64"
write_file /etc/openvpn/server/server.key    600 "$OVPN_KEY_B64"
write_file /etc/openvpn/server/tls-crypt.key 600 "$OVPN_TLSCRYPT_B64"
log "Wrote /etc/openvpn/server/ (fallback on TCP {site.ovpn_port})"
"""


def _linux_forwarding(site: Site) -> str:
    v6 = "net.ipv6.conf.all.forwarding = 1" if site.enable_ipv6 else ""
    return f"""
# ── IP forwarding ───────────────────────────────
# Without this the kernel silently drops every packet that arrives on the
# tunnel and is destined elsewhere — the tunnel comes up and carries nothing.
cat > {SYSCTL_PATH} <<'SYSCTL_EOF'
net.ipv4.ip_forward = 1
{v6}
SYSCTL_EOF
chmod 644 {SYSCTL_PATH}
sysctl -q -p {SYSCTL_PATH}
log "IP forwarding enabled."
"""


def _linux_nat(site: Site, subnets4: str, subnet6: str) -> str:
    """
    NAT lives in one helper script driven by a systemd unit.

    Putting it in wg-quick's PostUp would tie the rules to the WireGuard
    interface, leaving the OpenVPN subnet unrouted whenever WireGuard is down —
    exactly the situation the fallback exists for.
    """
    nat_script = f"""#!/usr/bin/env bash
# Generated by VPN Agent — NAT and forwarding rules for {site.name}.
set -euo pipefail

SUBNETS4="{subnets4}"
SUBNET6="{subnet6}"

wan_interface() {{
    ip route show default 2>/dev/null | awk '/^default/ {{ print $5; exit }}'
}}

WAN="${{VPN_AGENT_WAN:-$(wan_interface)}}"
[ -n "$WAN" ] || {{ echo "vpn-agent-nat: no default route; cannot determine WAN interface" >&2; exit 1; }}

# -C tests whether a rule exists; we add only when it does not, so re-running
# this script never stacks duplicate rules.
apply4() {{
    local table="$1"; shift
    iptables -t "$table" -C "$@" 2>/dev/null || iptables -t "$table" -A "$@"
}}

remove4() {{
    local table="$1"; shift
    while iptables -t "$table" -C "$@" 2>/dev/null; do
        iptables -t "$table" -D "$@"
    done
}}

apply6() {{
    local table="$1"; shift
    command -v ip6tables >/dev/null 2>&1 || return 0
    ip6tables -t "$table" -C "$@" 2>/dev/null || ip6tables -t "$table" -A "$@"
}}

remove6() {{
    local table="$1"; shift
    command -v ip6tables >/dev/null 2>&1 || return 0
    while ip6tables -t "$table" -C "$@" 2>/dev/null; do
        ip6tables -t "$table" -D "$@"
    done
}}

case "${{1:-up}}" in
  up)
    for net in $SUBNETS4; do
        apply4 nat POSTROUTING -s "$net" -o "$WAN" -j MASQUERADE
        apply4 filter FORWARD -s "$net" -j ACCEPT
        apply4 filter FORWARD -d "$net" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    done
    if [ -n "$SUBNET6" ]; then
        apply6 nat POSTROUTING -s "$SUBNET6" -o "$WAN" -j MASQUERADE
        apply6 filter FORWARD -s "$SUBNET6" -j ACCEPT
        apply6 filter FORWARD -d "$SUBNET6" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    fi
    echo "vpn-agent-nat: rules applied on $WAN"
    ;;
  down)
    for net in $SUBNETS4; do
        remove4 nat POSTROUTING -s "$net" -o "$WAN" -j MASQUERADE
        remove4 filter FORWARD -s "$net" -j ACCEPT
        remove4 filter FORWARD -d "$net" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    done
    if [ -n "$SUBNET6" ]; then
        remove6 nat POSTROUTING -s "$SUBNET6" -o "$WAN" -j MASQUERADE
        remove6 filter FORWARD -s "$SUBNET6" -j ACCEPT
        remove6 filter FORWARD -d "$SUBNET6" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    fi
    echo "vpn-agent-nat: rules removed"
    ;;
  status)
    echo "WAN: $WAN"
    iptables -t nat -S POSTROUTING | grep -F MASQUERADE || echo "(no masquerade rules)"
    ;;
  *)
    echo "usage: $0 {{up|down|status}}" >&2; exit 2 ;;
esac
"""

    nat_unit = f"""[Unit]
Description=VPN Agent NAT rules for {site.name}
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart={NAT_HELPER_PATH} up
ExecStop={NAT_HELPER_PATH} down

[Install]
WantedBy=multi-user.target
"""

    return f"""
# ── NAT ─────────────────────────────────────────
NAT_SCRIPT_B64='{_b64(nat_script)}'
NAT_UNIT_B64='{_b64(nat_unit)}'

write_file {NAT_HELPER_PATH} 755 "$NAT_SCRIPT_B64"
write_file {NAT_UNIT_PATH} 644 "$NAT_UNIT_B64"

systemctl daemon-reload
systemctl enable --quiet vpn-agent-nat.service
systemctl restart vpn-agent-nat.service
log "NAT rules applied and enabled at boot."
"""


def _linux_firewall(site: Site) -> str:
    ovpn_rule = (
        f'    ufw allow {site.ovpn_port}/tcp >/dev/null 2>&1 || true'
        if site.enable_openvpn
        else "    :"
    )
    return f"""
# ── Firewall ────────────────────────────────────
ufw_state=""
command -v ufw >/dev/null 2>&1 && ufw_state="$(ufw status 2>/dev/null || true)"

case "$ufw_state" in
*"Status: active"*)
    log "ufw is active — opening VPN ports."
    ufw allow {site.wg_port}/udp >/dev/null 2>&1 || true
{ovpn_rule}
    # Forwarding through ufw is denied by default; the VPN cannot route without this.
    if [ -f /etc/default/ufw ] && grep -q '^DEFAULT_FORWARD_POLICY="DROP"' /etc/default/ufw; then
        sed -i 's/^DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw
        ufw reload >/dev/null 2>&1 || true
        log "ufw forward policy set to ACCEPT."
    fi
    ;;
*)
    log "ufw not active — skipping firewall rules."
    ;;
esac
"""


def _linux_services(site: Site) -> str:
    ovpn_block = ""
    if site.enable_openvpn:
        ovpn_block = f"""
if systemctl cat openvpn-server@.service >/dev/null 2>&1; then
    systemctl enable --quiet openvpn-server@server.service
    systemctl restart openvpn-server@server.service
    log "OpenVPN fallback restarted (TCP {site.ovpn_port})."
else
    warn "openvpn-server@.service not found — OpenVPN may not be installed correctly."
fi
"""

    return f"""
# ── Services ────────────────────────────────────
# `wg syncconf` applies peer changes without tearing the interface down, so
# existing sessions survive a deploy that only adds a peer.
if wg show {site.wg_interface} >/dev/null 2>&1; then
    wg syncconf {site.wg_interface} <(wg-quick strip {site.wg_interface})
    log "WireGuard config reloaded in place (existing tunnels preserved)."
else
    systemctl enable --quiet wg-quick@{site.wg_interface}.service
    systemctl restart wg-quick@{site.wg_interface}.service
    log "WireGuard started on UDP {site.wg_port}."
fi
{ovpn_block}"""


def _linux_verify(site: Site) -> str:
    ovpn_check = ""
    if site.enable_openvpn:
        ovpn_check = f"""
if systemctl is-active --quiet openvpn-server@server.service; then
    log "  OpenVPN : active on TCP {site.ovpn_port}"
else
    warn "  OpenVPN : NOT running — check: journalctl -u openvpn-server@server -n 50"
    failed=1
fi
"""

    return f"""
# ── Verify ──────────────────────────────────────
failed=0
log "Verifying:"

if wg show {site.wg_interface} >/dev/null 2>&1; then
    log "  WireGuard: active on UDP {site.wg_port}"
else
    warn "  WireGuard: NOT running — check: journalctl -u wg-quick@{site.wg_interface} -n 50"
    failed=1
fi
{ovpn_check}
if [ "$(sysctl -n net.ipv4.ip_forward)" = "1" ]; then
    log "  Forwarding: enabled"
else
    warn "  Forwarding: DISABLED — traffic will not route"
    failed=1
fi

nat_rules="$(iptables -t nat -S POSTROUTING 2>/dev/null || true)"
case "$nat_rules" in
*MASQUERADE*)
    log "  NAT: masquerade rules present" ;;
*)
    warn "  NAT: no masquerade rule — clients will connect but reach nothing"
    failed=1 ;;
esac

detected_ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{{ print $7; exit }}' || true)"
[ -n "$detected_ip" ] && log "  Server egress address: $detected_ip"

if [ "$failed" -eq 0 ]; then
    log "Deploy complete — {site.name} is up."
else
    die "Deploy finished with problems (see warnings above)."
fi
"""


# ── macOS ────────────────────────────────────────


def macos_bootstrap(site: Site) -> str:
    """
    Render a native install script for macOS.

    macOS has no iptables, so NAT goes through pf. pf is configured by a single
    /etc/pf.conf, which is Apple's file and is reset by system updates — so this
    appends a marked block rather than replacing it, and the block is idempotent.

    Worth knowing before using this: a Mac makes a poor always-on VPN server.
    It sleeps, pf state is cleared by some updates, and the tunnel drops with
    the lid. A €50 Raspberry Pi running the Linux path is the better home
    server; this exists for testing and for a Mac that genuinely stays awake.
    """
    wg_conf = render.wg_server_config(site)
    nat_rules = _macos_pf_rules(site)

    ovpn_block = ""
    if site.enable_openvpn:
        ovpn_conf = render.ovpn_server_config(site)
        ovpn_block = f"""
# ── OpenVPN ─────────────────────────────────────
OVPN_DIR="$BREW_PREFIX/etc/openvpn"
mkdir -p "$OVPN_DIR"
chmod 700 "$OVPN_DIR"

write_file "$OVPN_DIR/server.conf"    644 '{_b64(ovpn_conf)}'
write_file "$OVPN_DIR/ca.crt"         644 '{_b64(site.ca_cert_pem)}'
write_file "$OVPN_DIR/server.crt"     644 '{_b64(site.server_cert_pem)}'
write_file "$OVPN_DIR/server.key"     600 '{_b64(site.server_key_pem)}'
write_file "$OVPN_DIR/tls-crypt.key"  600 '{_b64(site.tls_crypt_key)}'

# The config references its material by bare filename, so OpenVPN must be
# started with that directory as its working directory.
sed -i '' "s|^status .*|status $OVPN_DIR/status.log|" "$OVPN_DIR/server.conf"
# user/group nobody:nogroup is Linux naming; macOS uses nobody:nobody.
sed -i '' "s|^group nogroup|group nobody|" "$OVPN_DIR/server.conf"

log "OpenVPN config written to $OVPN_DIR"
log "Start it with:  sudo openvpn --cd $OVPN_DIR --config server.conf --daemon"
"""

    return f"""#!/usr/bin/env bash
#
# {site.name} — native VPN server bootstrap (macOS)
# Generated by VPN Agent. Idempotent: safe to re-run.

set -euo pipefail
umask 077

log()  {{ printf '\\033[36m[vpn-agent]\\033[0m %s\\n' "$*"; }}
warn() {{ printf '\\033[33m[vpn-agent] WARN:\\033[0m %s\\n' "$*" >&2; }}
die()  {{ printf '\\033[31m[vpn-agent] ERROR:\\033[0m %s\\n' "$*" >&2; exit 1; }}

[ "$(id -u)" -eq 0 ] || die "This script must run as root (use sudo)."

if printf 'dGVzdA==' | base64 --decode >/dev/null 2>&1; then
    B64D="base64 --decode"
else
    B64D="base64 -D"
fi

write_file() {{
    local dest="$1" mode="$2" payload="$3"
    mkdir -p "$(dirname "$dest")"
    printf '%s' "$payload" | $B64D > "$dest.tmp"
    chmod "$mode" "$dest.tmp"
    mv -f "$dest.tmp" "$dest"
}}

# Homebrew runs as the invoking user, not root.
REAL_USER="${{SUDO_USER:-$(whoami)}}"
BREW_BIN="$(sudo -u "$REAL_USER" command -v brew 2>/dev/null || true)"
[ -n "$BREW_BIN" ] || die "Homebrew not found. Install it first: https://brew.sh"
BREW_PREFIX="$(sudo -u "$REAL_USER" "$BREW_BIN" --prefix)"

log "Configuring {site.name} natively on macOS (prefix $BREW_PREFIX)"

# ── Packages ────────────────────────────────────
for formula in wireguard-tools{' openvpn' if site.enable_openvpn else ''}; do
    if sudo -u "$REAL_USER" "$BREW_BIN" list --formula "$formula" >/dev/null 2>&1; then
        log "$formula already installed."
    else
        log "Installing $formula…"
        sudo -u "$REAL_USER" "$BREW_BIN" install "$formula"
    fi
done

# ── WireGuard ───────────────────────────────────
WG_DIR="$BREW_PREFIX/etc/wireguard"
mkdir -p "$WG_DIR"
chmod 700 "$WG_DIR"
write_file "$WG_DIR/{site.wg_interface}.conf" 600 '{_b64(wg_conf)}'
log "Wrote $WG_DIR/{site.wg_interface}.conf"
{ovpn_block}
# ── Forwarding ──────────────────────────────────
sysctl -w net.inet.ip.forwarding=1 >/dev/null
{'sysctl -w net.inet6.ip6.forwarding=1 >/dev/null' if site.enable_ipv6 else ''}
log "IP forwarding enabled (resets on reboot — see docs for the launchd unit)."

# ── NAT via pf ──────────────────────────────────
WAN="$(route -n get default 2>/dev/null | awk '/interface:/ {{ print $2; exit }}')"
[ -n "$WAN" ] || die "Could not determine the default network interface."
log "Egress interface: $WAN"

write_file {PF_ANCHOR_PATH} 644 '{_b64(nat_rules)}'
sed -i '' "s|__WAN__|$WAN|g" {PF_ANCHOR_PATH}

# Append our anchor to /etc/pf.conf between markers, replacing any previous
# block. Apple owns this file and system updates overwrite it — re-run this
# script after a major macOS update.
if ! grep -qF '{PF_MARKER}' /etc/pf.conf; then
    cp /etc/pf.conf /etc/pf.conf.vpn-agent.bak
    cat >> /etc/pf.conf <<'PFEOF'
{PF_MARKER}
nat-anchor "vpn-agent"
anchor "vpn-agent"
load anchor "vpn-agent" from "{PF_ANCHOR_PATH}"
# <<< vpn-agent <<<
PFEOF
    log "Registered pf anchor in /etc/pf.conf (backup: /etc/pf.conf.vpn-agent.bak)"
else
    log "pf anchor already registered."
fi

pfctl -f /etc/pf.conf 2>&1 | grep -v "^No ALTQ" || true
pfctl -e 2>&1 | grep -v "already enabled" || true
log "pf reloaded."

# ── Start ───────────────────────────────────────
if wg show {site.wg_interface} >/dev/null 2>&1; then
    wg syncconf {site.wg_interface} <(wg-quick strip "$WG_DIR/{site.wg_interface}.conf")
    log "WireGuard reloaded in place."
else
    wg-quick up "$WG_DIR/{site.wg_interface}.conf"
    log "WireGuard started on UDP {site.wg_port}."
fi

log "Done. Native servers on macOS stop when the Mac sleeps —"
log "check System Settings › Energy for 'Prevent automatic sleeping'."
"""


def _macos_pf_rules(site: Site) -> str:
    """pf anchor body. __WAN__ is substituted at install time."""
    lines = [
        f"# {site.name} — VPN Agent NAT anchor",
        "# __WAN__ is replaced with the live default interface by the installer.",
        "",
    ]
    for subnet in site.natted_subnets():
        net = ipaddress.ip_network(subnet, strict=False)
        lines.append(f"nat on __WAN__ from {net} to any -> (__WAN__)")
    lines += [
        "",
        "pass in quick on utun0 all",
        "pass out quick on __WAN__ all",
    ]
    return "\n".join(lines) + "\n"


def pf_conf_has_marker() -> bool:
    """
    True if our block is still present in /etc/pf.conf.

    Apple owns that file and a macOS update rewrites it, silently dropping the
    anchor and with it the NAT rules a native server depends on. The tunnel
    still comes up afterwards and carries nothing, which is a confusing way to
    fail — so the app checks and says so rather than leaving you to work it out.
    """
    try:
        return PF_MARKER in Path("/etc/pf.conf").read_text(encoding="utf-8")
    except OSError:
        return False


def macos_teardown_script(site: Site) -> str:
    """
    Remove a native macOS install.

    The pf block is cut out by marker rather than by rewriting the file, so
    anything else in /etc/pf.conf — Apple's own anchors included — is left
    exactly as it was.
    """
    ovpn = ""
    if site.enable_openvpn:
        ovpn = (
            'pkill -f "openvpn --cd" 2>/dev/null || true\n'
            'rm -f "$BREW_PREFIX/etc/openvpn/server.conf" '
            '"$BREW_PREFIX/etc/openvpn/ca.crt" '
            '"$BREW_PREFIX/etc/openvpn/server.crt" '
            '"$BREW_PREFIX/etc/openvpn/server.key" '
            '"$BREW_PREFIX/etc/openvpn/tls-crypt.key"\n'
            'echo "[vpn-agent] OpenVPN removed."\n'
        )

    return f"""#!/usr/bin/env bash
# Remove the {site.name} VPN server from this Mac. Generated by VPN Agent.
set -uo pipefail

[ "$(id -u)" -eq 0 ] || {{ echo "Must run as root." >&2; exit 1; }}

REAL_USER="${{SUDO_USER:-$(whoami)}}"
BREW_BIN="$(sudo -u "$REAL_USER" command -v brew 2>/dev/null || true)"
BREW_PREFIX="$(sudo -u "$REAL_USER" "$BREW_BIN" --prefix 2>/dev/null || echo /opt/homebrew)"

wg-quick down "$BREW_PREFIX/etc/wireguard/{site.wg_interface}.conf" 2>/dev/null || true
rm -f "$BREW_PREFIX/etc/wireguard/{site.wg_interface}.conf"
echo "[vpn-agent] WireGuard removed."

{ovpn}
# Cut our block out of /etc/pf.conf by marker, leaving everything else intact.
if grep -qF '{PF_MARKER}' /etc/pf.conf 2>/dev/null; then
    cp /etc/pf.conf /etc/pf.conf.vpn-agent-teardown.bak
    awk '{PF_STRIP_AWK}' \\
        /etc/pf.conf.vpn-agent-teardown.bak > /etc/pf.conf
    echo "[vpn-agent] pf anchor unregistered (backup: /etc/pf.conf.vpn-agent-teardown.bak)."
fi
rm -f {PF_ANCHOR_PATH}

pfctl -f /etc/pf.conf 2>&1 | grep -v "^No ALTQ" || true
echo "[vpn-agent] pf reloaded."

# Forwarding was only set at runtime on macOS so it reverts on reboot anyway;
# turning it off now makes the change immediate.
sysctl -w net.inet.ip.forwarding=0 >/dev/null 2>&1 || true

echo "[vpn-agent] Teardown complete. Homebrew formulae were left installed."
"""


def bootstrap_for(site: Site, platform: str) -> str:
    """Return the right installer for a target platform ('linux' or 'darwin')."""
    if platform == "darwin":
        return macos_bootstrap(site)
    if platform == "linux":
        return linux_bootstrap(site)
    raise ValueError(f"Unsupported target platform {platform!r}; expected 'linux' or 'darwin'.")
