"""
obfuscation.py — Making the server harder to identify and easier to reach.

Two independent mechanisms, solving two different problems.

**stunnel** answers "this network can see I am speaking OpenVPN and is blocking
it." OpenVPN already uses tls-crypt, which hides the handshake's contents, but
the packet sizes and timing of an OpenVPN session are still recognisable to a
deep-packet inspector that is looking. stunnel puts a real TLS listener on the
public port and forwards to OpenVPN bound to loopback, so what crosses the
network is an ordinary TLS session on 443 — not resembling HTTPS, actually
being HTTPS as far as the wire is concerned.

The cost is honest and non-trivial: the client needs stunnel running locally
too. The .ovpn then connects to 127.0.0.1, and stunnel carries it the rest of
the way. That is one more moving part on every device, which is why this is off
by default.

**An onion service** answers "my server has no public address." Behind CGNAT,
or on a home connection whose ISP will not forward ports, there is no address
to dial and no amount of dynamic DNS fixes it. A hidden service is reachable
without one, because the rendezvous happens inside the Tor network. It also
means the server's real address is never revealed to a client.

Onion services carry TCP only, so they front the OpenVPN fallback rather than
WireGuard. It is slower than the direct path — Tor always is — and it is a
route of last resort rather than an everyday one.

Neither of these makes you anonymous. They make the connection harder to block
and harder to attribute in transit; the server is still rented in your name.
"""

from __future__ import annotations

import base64

from .model import OBFS_STUNNEL, Site

STUNNEL_SERVICE = "vpn-agent-openvpn"
ONION_DIR = "/var/lib/tor/vpn-agent-openvpn"


def _b64(text: str) -> str:
    return base64.standard_b64encode(text.encode("utf-8")).decode("ascii")


# ── stunnel ──────────────────────────────────────


def stunnel_server_config(site: Site) -> str:
    """
    The server half: accept TLS on the public port, forward to OpenVPN on
    loopback.

    The certificate is issued by the site's own CA, so a client can verify the
    server rather than accepting anything that answers. Without that check,
    anyone able to intercept the connection could terminate the TLS themselves
    — which would defeat the point of adding it.
    """
    return f"""; {site.name} — stunnel in front of OpenVPN.
; Generated by VPN Agent. Edits are overwritten on the next deploy.

foreground = no
pid = /var/run/stunnel-vpn-agent.pid
output = /var/log/stunnel4/vpn-agent.log

; Drop privileges once the port is bound.
setuid = stunnel4
setgid = stunnel4

[{STUNNEL_SERVICE}]
accept = {site.ovpn_port}
connect = 127.0.0.1:{site.ovpn_local_port}

cert = /etc/stunnel/vpn-agent.crt
key = /etc/stunnel/vpn-agent.key

; TLS 1.2 is the floor; anything older is both weaker and, by now, unusual
; enough on the wire to be its own signal.
sslVersionMin = TLSv1.2
ciphers = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
"""


def stunnel_client_config(site: Site) -> str:
    """
    The client half, handed to the user alongside the .ovpn.

    verifyChain pins the connection to the site's own CA. Left off, stunnel
    would happily connect to anything presenting any certificate.
    """
    return f"""; {site.name} — stunnel client for the OpenVPN fallback.
;
; Run this, then point the .ovpn at 127.0.0.1:{site.ovpn_local_port}:
;     stunnel /path/to/this/file
;
; The .ovpn exported alongside it is already configured that way.

foreground = yes
output = /dev/stdout

[{STUNNEL_SERVICE}]
client = yes
accept = 127.0.0.1:{site.ovpn_local_port}
connect = {site.endpoint_host}:{site.ovpn_port}

; Verify the server against the site's own certificate authority. Without
; this, stunnel accepts any certificate at all and the TLS layer proves
; nothing about who is on the other end.
verifyChain = yes
CAfile = ca.crt
checkHost = {site.name.lower().replace(" ", "-")}-server

sslVersionMin = TLSv1.2
"""


def linux_stunnel_section(site: Site) -> str:
    """Installer section that sets stunnel up. Empty unless it is enabled."""
    if site.obfuscation != OBFS_STUNNEL:
        return ""

    return f"""
# ── stunnel (TLS obfuscation) ───────────────────
status="$(dpkg-query -W -f='${{Status}}' stunnel4 2>/dev/null || true)"
case "$status" in
    "install ok installed") log "stunnel4 already present." ;;
    *)
        log "Installing stunnel4"
        export DEBIAN_FRONTEND=noninteractive
        apt-get install -y -qq stunnel4
        ;;
esac

STUNNEL_CONF_B64='{_b64(stunnel_server_config(site))}'
STUNNEL_CERT_B64='{_b64(site.server_cert_pem)}'
STUNNEL_KEY_B64='{_b64(site.server_key_pem)}'

mkdir -p /etc/stunnel /var/log/stunnel4
chown stunnel4:stunnel4 /var/log/stunnel4 2>/dev/null || true

write_file /etc/stunnel/vpn-agent.conf 644 "$STUNNEL_CONF_B64"
write_file /etc/stunnel/vpn-agent.crt  644 "$STUNNEL_CERT_B64"
write_file /etc/stunnel/vpn-agent.key  600 "$STUNNEL_KEY_B64"
chown stunnel4:stunnel4 /etc/stunnel/vpn-agent.key 2>/dev/null || true

# Debian ships stunnel4 disabled until this is flipped.
if [ -f /etc/default/stunnel4 ]; then
    sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/stunnel4
fi

systemctl enable --quiet stunnel4 2>/dev/null || true
systemctl restart stunnel4 2>/dev/null || true
log "stunnel listening on TCP {site.ovpn_port}, forwarding to OpenVPN on 127.0.0.1:{site.ovpn_local_port}."
"""


# ── Onion service ────────────────────────────────


def linux_onion_section(site: Site) -> str:
    """Installer section that publishes the OpenVPN port as an onion service."""
    if not site.onion_enabled:
        return ""

    # Whatever is actually facing the world: stunnel if it is in front,
    # OpenVPN itself otherwise.
    target_port = site.ovpn_port if site.obfuscation == OBFS_STUNNEL else site.ovpn_bind_port

    return f"""
# ── Tor onion service ───────────────────────────
status="$(dpkg-query -W -f='${{Status}}' tor 2>/dev/null || true)"
case "$status" in
    "install ok installed") log "tor already present." ;;
    *)
        log "Installing tor"
        export DEBIAN_FRONTEND=noninteractive
        apt-get install -y -qq tor
        ;;
esac

# Appended between markers so Tor's own packaged config is left intact and a
# re-run replaces our block rather than stacking another copy.
python3 - <<'ONION_PY'
from pathlib import Path

START = "# >>> vpn-agent onion >>>"
END = "# <<< vpn-agent onion <<<"
block = "\\n".join([
    START,
    "HiddenServiceDir {ONION_DIR}",
    "HiddenServicePort {target_port} 127.0.0.1:{target_port}",
    END,
])

path = Path("/etc/tor/torrc")
text = path.read_text() if path.exists() else ""
if START in text and END in text:
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    text = head + block + tail
else:
    text = text.rstrip() + "\\n\\n" + block + "\\n"
path.write_text(text)
ONION_PY

mkdir -p {ONION_DIR}
chown -R debian-tor:debian-tor {ONION_DIR} 2>/dev/null || true
chmod 700 {ONION_DIR}

systemctl enable --quiet tor 2>/dev/null || true
systemctl restart tor 2>/dev/null || true

# Tor writes the hostname a moment after starting.
for _ in $(seq 1 20); do
    [ -f {ONION_DIR}/hostname ] && break
    sleep 1
done

if [ -f {ONION_DIR}/hostname ]; then
    log "Onion address: $(cat {ONION_DIR}/hostname)"
    log "VPN_AGENT_ONION=$(cat {ONION_DIR}/hostname)"
else
    warn "Tor did not publish an onion address — check: journalctl -u tor -n 50"
fi
"""


def parse_onion_address(deploy_output: str) -> str:
    """
    Pull the onion address out of a deploy log.

    The installer echoes it on a line of its own precisely so it can be picked
    up here and stored against the site — otherwise it exists only on the
    server and the user has to go and read a file to learn their own address.
    """
    for line in deploy_output.splitlines():
        if "VPN_AGENT_ONION=" in line:
            candidate = line.split("VPN_AGENT_ONION=", 1)[1].strip()
            if candidate.endswith(".onion"):
                return candidate
    return ""


# ── Client-side guidance ─────────────────────────


def client_instructions(site: Site) -> str:
    """What the user has to do on the device, in the order they have to do it."""
    if site.obfuscation != OBFS_STUNNEL and not site.onion_enabled:
        return ""

    lines: list[str] = []
    if site.obfuscation == OBFS_STUNNEL:
        lines += [
            "This server fronts OpenVPN with stunnel, so the device needs stunnel too:",
            "",
            "  1. brew install stunnel        (macOS)  /  apt install stunnel4  (Linux)",
            "  2. Save the exported stunnel-client.conf and ca.crt side by side.",
            "  3. Run:  stunnel /path/to/stunnel-client.conf",
            f"  4. Import the .ovpn — it already points at 127.0.0.1:{site.ovpn_local_port}.",
            "",
            "Leave stunnel running while the tunnel is up. WireGuard is unaffected and",
            "still connects directly.",
        ]
    if site.onion_enabled:
        if lines:
            lines.append("")
        address = site.onion_address or "<published on first deploy>"
        lines += [
            "An onion service is published for this server:",
            "",
            f"  {address}:{site.ovpn_port}",
            "",
            "Reaching it needs Tor running on the device, with OpenVPN pointed through",
            "Tor's SOCKS port. Slower than the direct route — this is the path for when",
            "the server has no public address, or the direct one is blocked.",
        ]
    return "\n".join(lines) + "\n"
