"""
render.py — Turning a Site into the four config files that matter.

Two servers and two clients:

  wg_server_config    /etc/wireguard/wg0.conf
  wg_client_config    the .conf a device imports
  ovpn_server_config  /etc/openvpn/server/server.conf
  ovpn_client_config  the .ovpn a device imports, with keys inlined

A few choices here are load-bearing rather than stylistic, and are commented
where they occur — the ones that silently break a tunnel if you get them wrong
are `explicit-exit-notify` on TCP, the client-side `AllowedIPs`, and the MTU.
"""

from __future__ import annotations

import ipaddress

from .model import Peer, Site

# 1500 (typical ethernet MTU) minus 60 bytes of IPv6+UDP+WireGuard overhead.
# Too high and large packets vanish into a black hole on any path that will not
# fragment; this value is what wg-quick itself picks on a normal link.
WG_MTU = 1420

# OpenVPN over TCP: cap the TCP MSS so the encapsulated segments still fit
# inside the outer path MTU without relying on path-MTU discovery, which is
# routinely broken by firewalls that drop ICMP.
OVPN_MSSFIX = 1300

DATA_CIPHERS = "AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305"


# ── WireGuard ────────────────────────────────────


def wg_server_config(site: Site) -> str:
    """Render the server's wg0.conf."""
    addresses = [site.server_address4]
    if site.enable_ipv6:
        addresses.append(site.server_address6)

    lines = [
        f"# {site.name} — WireGuard server",
        "# Generated by VPN Agent. Edits here are overwritten on the next deploy.",
        "#",
        "# NAT and forwarding are not configured here: they live in the",
        "# vpn-agent-nat systemd unit so the OpenVPN fallback shares the exact",
        "# same rules instead of each transport carrying its own copy.",
        "",
        "[Interface]",
        f"Address = {', '.join(addresses)}",
        f"ListenPort = {site.wg_port}",
        f"PrivateKey = {site.server_wg_private_key}",
        f"MTU = {WG_MTU}",
    ]

    active = [p for p in site.peers if p.enabled]
    for peer in active:
        lines += [
            "",
            f"# {peer.name}" + (f" — {peer.notes}" if peer.notes else ""),
            "[Peer]",
            f"PublicKey = {peer.wg_public_key}",
            f"PresharedKey = {peer.wg_preshared_key}",
            # This is an access-control rule as much as a route: the server
            # drops any packet arriving from this peer with a source address
            # outside this list.
            f"AllowedIPs = {site.server_allowed_ips(peer)}",
        ]

    if not active:
        lines += ["", "# No enabled peers — nothing can connect to this server yet."]

    return "\n".join(lines) + "\n"


def wg_client_config(site: Site, peer: Peer) -> str:
    """Render the .conf a client device imports."""
    addresses = [peer.address4]
    if site.enable_ipv6 and peer.address6:
        addresses.append(peer.address6)

    lines = [
        f"# {peer.name} → {site.name}",
        "# Generated by VPN Agent. Contains a private key — treat it as a password.",
        "",
        "[Interface]",
        f"PrivateKey = {peer.wg_private_key}",
        f"Address = {', '.join(addresses)}",
        f"MTU = {WG_MTU}",
    ]

    if site.dns:
        # Without this the client keeps using whatever resolver the local
        # network handed it, so the tunnel hides the traffic but the DNS
        # lookups still announce every site visited.
        lines.append(f"DNS = {', '.join(site.dns)}")

    lines += [
        "",
        "[Peer]",
        f"PublicKey = {site.server_wg_public_key}",
        f"PresharedKey = {peer.wg_preshared_key}",
        f"AllowedIPs = {site.client_allowed_ips()}",
        f"Endpoint = {_endpoint(site.endpoint_host, site.wg_port)}",
        # Holds the NAT mapping open from behind a home router so the server
        # can reach the client without the client speaking first.
        "PersistentKeepalive = 25",
    ]
    return "\n".join(lines) + "\n"


# ── OpenVPN ──────────────────────────────────────


def ovpn_server_config(site: Site) -> str:
    """Render the OpenVPN server config for the TCP fallback."""
    net = ipaddress.ip_network(site.ovpn_subnet4, strict=False)

    fronted = site.ovpn_binds_loopback_only

    lines = [
        f"# {site.name} — OpenVPN fallback",
        "# Generated by VPN Agent. Edits here are overwritten on the next deploy.",
        "",]
    if fronted:
        lines += [
            "# stunnel holds the public port and forwards here. Binding to loopback",
            "# is what makes that a real boundary: without it OpenVPN would also be",
            "# reachable directly, and the obfuscation would be trivially bypassed —",
            "# by a scanner as easily as by you.",
            "local 127.0.0.1",
            "",
        ]
    lines += [
        f"port {site.ovpn_bind_port}",
        # TCP, not UDP: the entire reason this endpoint exists is to survive
        # networks that pass only what looks like web traffic.
        "proto tcp-server",
        "dev tun",
        "topology subnet",
        f"server {net.network_address} {net.netmask}",
        "",
        "ca ca.crt",
        "cert server.crt",
        "key server.key",
        "tls-crypt tls-crypt.key",
        # The certificates are P-256, so there are no Diffie-Hellman parameters
        # to generate — this is what keeps install time in seconds.
        "dh none",
        "ecdh-curve prime256v1",
        "tls-version-min 1.2",
        # Reject anything not holding a clientAuth certificate from our CA.
        "remote-cert-tls client",
        "",
        f"data-ciphers {DATA_CIPHERS}",
        "data-ciphers-fallback AES-256-GCM",
        "auth SHA256",
        f"mssfix {OVPN_MSSFIX}",
        "",
        "keepalive 10 120",
        "persist-key",
        "persist-tun",
        # Drop privileges once the tunnel device is open.
        "user nobody",
        "group nogroup",
        "",
        "status /var/log/openvpn/status.log",
        "verb 3",
        # Deliberately absent: explicit-exit-notify. It is a UDP-only directive
        # and OpenVPN refuses to start with it under proto tcp-server.
    ]

    if site.full_tunnel:
        lines += [
            "",
            'push "redirect-gateway def1 bypass-dhcp"',
            # This tunnel is IPv4-only — there is no server-ipv6 pool, so there
            # is nowhere to send IPv6. Without blocking it, a dual-stack client
            # keeps reaching IPv6 destinations over its native connection,
            # outside the tunnel, leaking exactly what the tunnel is for.
            'push "block-ipv6"',
        ]
    else:
        lines.append("")
        for route in [site.wg_subnet4, *site.lan_routes]:
            if not route:
                continue
            route_net = ipaddress.ip_network(route, strict=False)
            lines.append(f'push "route {route_net.network_address} {route_net.netmask}"')

    for resolver in site.dns:
        lines.append(f'push "dhcp-option DNS {resolver}"')

    return "\n".join(lines) + "\n"


def ovpn_client_config(site: Site, peer: Peer) -> str:
    """Render a self-contained .ovpn profile with all key material inlined."""
    if not peer.has_openvpn:
        raise ValueError(
            f"Peer {peer.name!r} has no OpenVPN certificate. "
            "Enable OpenVPN on the site and re-add or rotate the peer."
        )

    lines = [
        f"# {peer.name} → {site.name} (OpenVPN fallback)",
        "# Use this when the WireGuard tunnel cannot establish — typically a",
        "# network that blocks UDP. Slower, but it looks like ordinary HTTPS.",
        "",]
    if site.ovpn_binds_loopback_only:
        lines_prefix = [
            "# This server is fronted by stunnel, so this profile connects to a local",
            "# stunnel rather than to the server directly. Start stunnel first with the",
            "# stunnel-client.conf exported alongside this file, or the connection will",
            "# be refused by nothing at all — there is no listener on 127.0.0.1 yet.",
            "",
        ]
    else:
        lines_prefix = []
    lines = lines[:-1] + lines_prefix + [
        "client",
        "dev tun",
        "proto tcp-client",
        (
            f"remote 127.0.0.1 {site.ovpn_local_port}"
            if site.ovpn_binds_loopback_only
            else f"remote {site.endpoint_host} {site.ovpn_port}"
        ),
        "resolv-retry infinite",
        "nobind",
        "persist-key",
        "persist-tun",
        "",
        # Pins the server to a serverAuth certificate, so a stolen *client*
        # certificate from this same CA cannot be used to impersonate the server.
        "remote-cert-tls server",
        "tls-version-min 1.2",
        f"data-ciphers {DATA_CIPHERS}",
        "data-ciphers-fallback AES-256-GCM",
        "auth SHA256",
        f"mssfix {OVPN_MSSFIX}",
        "verb 3",
        "",
        _inline("ca", site.ca_cert_pem),
        _inline("cert", peer.ovpn_cert_pem),
        _inline("key", peer.ovpn_key_pem),
        _inline("tls-crypt", site.tls_crypt_key),
    ]
    return "\n".join(lines) + "\n"


# ── Helpers ──────────────────────────────────────


def _inline(tag: str, body: str) -> str:
    return f"<{tag}>\n{body.strip()}\n</{tag}>\n"


def _endpoint(host: str, port: int) -> str:
    """Format host:port, bracketing bare IPv6 literals."""
    host = (host or "").strip()
    try:
        if isinstance(ipaddress.ip_address(host), ipaddress.IPv6Address):
            return f"[{host}]:{port}"
    except ValueError:
        pass
    return f"{host}:{port}"
