"""
proxychain.py — Routing through several proxies in sequence.

A chain means each hop only learns the address of the next one, so no single
proxy sees both who you are and where you are going. That is the real benefit,
and it is a narrow one: chaining slow proxies makes everything slower, and a
chain of proxies you do not control is a chain of parties who can log you.

Two honest limits worth knowing before relying on this:

  **On macOS, proxychains-ng barely works.** It functions by injecting a
  library with DYLD_INSERT_LIBRARIES, and System Integrity Protection strips
  that variable from anything Apple ships — every system binary, and anything
  in /usr/bin or /bin. It can still wrap a Homebrew binary you built yourself.
  Curl from /usr/bin will simply ignore it and connect directly, which looks
  exactly like it worked.

  **Chains carry TCP only.** UDP, and therefore ordinary DNS and QUIC, does not
  traverse SOCKS in any way these tools implement. Anything relying on UDP
  either fails or quietly bypasses the chain.

Because of the first point, this module does not rely on proxychains for
anything the app itself does. The chain is spoken natively — see
socks_client.connect_through — so testing a chain and using it for the app's
own checks works regardless of SIP. The generated proxychains.conf is offered
for other programs, with the caveat attached.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path

from agents.vpn_agent.server import paths
from agents.vpn_agent.services.socks_client import (
    HTTP,
    SOCKS4,
    SOCKS5,
    ProxyHop,
    SocksError,
    http_get_through,
)

STRICT = "strict"
DYNAMIC = "dynamic"
RANDOM = "random"
MODES = (STRICT, DYNAMIC, RANDOM)

# Plain HTTP and a body that is only an address — small, and no TLS needed to
# read it, so a probe failure is a chain failure rather than a certificate one.
PROBE_HOST = "api.ipify.org"
PROBE_PATH = "/"


@dataclass
class Chain:
    """An ordered list of proxies, plus how proxychains should treat them."""

    name: str = "default"
    hops: list[ProxyHop] = field(default_factory=list)
    mode: str = STRICT
    enabled: bool = False
    proxy_dns: bool = True

    def problems(self) -> list[str]:
        issues: list[str] = []
        if self.mode not in MODES:
            issues.append(f"unknown chain mode {self.mode!r}")
        if not self.hops:
            issues.append("the chain has no proxies in it")
        for index, hop in enumerate(self.hops, start=1):
            for problem in hop.problems():
                issues.append(f"hop {index}: {problem}")
        if not self.proxy_dns:
            issues.append(
                "DNS is not being sent through the chain, so every lookup names "
                "the host you are about to visit to your ISP's resolver"
            )
        return issues

    def describe(self) -> str:
        if not self.hops:
            return "(empty)"
        return "  →  ".join(hop.describe() for hop in self.hops)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "mode": self.mode,
            "enabled": self.enabled,
            "proxy_dns": self.proxy_dns,
            "hops": [hop.to_dict() for hop in self.hops],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Chain":
        chain = cls(
            name=data.get("name", "default"),
            mode=data.get("mode", STRICT),
            enabled=bool(data.get("enabled", False)),
            proxy_dns=bool(data.get("proxy_dns", True)),
        )
        chain.hops = [ProxyHop.from_dict(h) for h in data.get("hops", [])]
        return chain


# ── Storage ──────────────────────────────────────


def chain_path() -> Path:
    return paths.state_dir() / "proxychain.json"


def load_chain() -> Chain:
    path = chain_path()
    if not path.is_file():
        return Chain()
    try:
        return Chain.from_dict(json.loads(path.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError, TypeError):
        return Chain()


def save_chain(chain: Chain) -> Path:
    path = chain_path()
    paths.ensure_private_dir(path.parent)
    # Proxy credentials live in here, so it is owner-only like the site files.
    return paths.write_private(path, json.dumps(chain.to_dict(), indent=2))


# ── proxychains-ng config ────────────────────────


def render_proxychains_conf(chain: Chain) -> str:
    """
    Render a proxychains-ng configuration.

    Provided for wrapping other programs. Read the SIP caveat at the top of this
    module before trusting it on macOS.
    """
    lines = [
        f"# {chain.name} — generated by VPN Agent.",
        "#",
        "# macOS caveat: proxychains-ng works by injecting a library through",
        "# DYLD_INSERT_LIBRARIES, and System Integrity Protection strips that",
        "# from every Apple-shipped binary. /usr/bin/curl will ignore this file",
        "# entirely and connect directly — which looks identical to success.",
        "# Verify with a binary you installed yourself, and check the exit IP.",
        "",
        f"{chain.mode}_chain",
    ]

    if chain.mode == RANDOM:
        lines.append("chain_len = 2")

    lines += [
        "",
        "proxy_dns" if chain.proxy_dns else "# proxy_dns disabled — DNS will leak",
        "",
        "tcp_read_time_out 15000",
        "tcp_connect_time_out 10000",
        "",
        "[ProxyList]",
    ]

    for hop in chain.hops:
        entry = f"{hop.kind} {hop.host} {hop.port}"
        if hop.username:
            entry += f" {hop.username} {hop.password}"
        lines.append(entry)

    if not chain.hops:
        lines.append("# (no proxies configured — proxychains will refuse to run)")

    return "\n".join(lines) + "\n"


def write_proxychains_conf(chain: Chain, path: Path | None = None) -> Path:
    target = path or (paths.state_dir() / "proxychains.conf")
    paths.ensure_private_dir(target.parent)
    # May hold proxy credentials.
    return paths.write_private(target, render_proxychains_conf(chain))


# ── Testing a chain ──────────────────────────────


@dataclass
class ProbeResult:
    ok: bool
    exit_ip: str = ""
    elapsed_ms: int = 0
    error: str = ""
    hop_reached: int = 0          # how many hops were negotiated before failing

    def summary(self) -> str:
        if self.ok:
            return f"Chain works — traffic exits at {self.exit_ip} ({self.elapsed_ms} ms)"
        where = f" (failed at hop {self.hop_reached})" if self.hop_reached else ""
        return f"Chain failed{where}: {self.error}"


def probe(chain: Chain, timeout: float = 20.0) -> ProbeResult:
    """
    Actually run traffic through the chain and report where it comes out.

    Speaks SOCKS directly rather than shelling out to proxychains, so this is a
    real end-to-end test even on a Mac where SIP would defeat the wrapper.
    """
    problems = [p for p in chain.problems() if "DNS" not in p]
    if problems:
        return ProbeResult(False, error="; ".join(problems))

    started = time.time()
    try:
        body = http_get_through(chain.hops, PROBE_HOST, PROBE_PATH, port=80, timeout=timeout)
    except SocksError as exc:
        message = str(exc)
        hop_number = 0
        if message.startswith("hop "):
            try:
                hop_number = int(message.split()[1])
            except (IndexError, ValueError):
                pass
        return ProbeResult(False, error=message, hop_reached=hop_number)
    except OSError as exc:
        return ProbeResult(False, error=f"could not reach the first proxy: {exc}")

    elapsed = int((time.time() - started) * 1000)
    exit_ip = body.strip().splitlines()[-1].strip() if body.strip() else ""
    if not exit_ip or len(exit_ip) > 45:
        return ProbeResult(False, error="the chain returned something unreadable",
                           elapsed_ms=elapsed)
    return ProbeResult(True, exit_ip=exit_ip, elapsed_ms=elapsed)


def wrap_command(chain: Chain, command: list[str], conf: Path | None = None) -> list[str]:
    """
    Build the argv that runs a command through proxychains.

    Returned rather than executed, so a caller can show it to the user before
    anything runs.
    """
    path = conf or (paths.state_dir() / "proxychains.conf")
    return ["proxychains4", "-q", "-f", str(path), *command]
