"""
tor.py — A local Tor daemon, managed by the app.

What this is for, stated plainly, because Tor and VPNs are combined more often
than they are understood:

  Running the VPN *and* Tor means your traffic enters the tunnel, leaves at your
  server, and only then enters the Tor network. Tor's guard node therefore sees
  your server's address instead of your home one, and your ISP sees only
  WireGuard. That is the useful direction.

  It does not make you anonymous. Your server is rented in your name, the exit
  node still sees whatever is not end-to-end encrypted, and a single-user server
  is a far better fingerprint than a crowd. Adding Tor to a VPN mostly moves
  which party has to be subpoenaed.

  Anything you actually need Tor's anonymity for should use Tor Browser, whose
  fingerprinting defences are the hard part and are absent from every other
  application.

Practical notes on the implementation:

  Ports 9250/9251 rather than Tor's usual 9050/9051, so this never fights a
  system Tor or Tor Browser (9150) already running.

  Tor runs as an ordinary child process with our own torrc under Application
  Support. No sudo, nothing installed system-wide, and quitting the app can
  clean up after itself.
"""

from __future__ import annotations

import os
import shutil
import signal
import socket
import subprocess
import time
from pathlib import Path

from agents.vpn_agent.server import paths
from agents.vpn_agent.services.socks_client import ProxyHop, SOCKS5, SocksError, http_get_through

SOCKS_PORT = 9250
CONTROL_PORT = 9251

STARTUP_TIMEOUT = 60          # a first bootstrap on a slow link genuinely takes this
SHUTDOWN_TIMEOUT = 10
CHECK_HOST = "check.torproject.org"


class TorError(Exception):
    pass


# ── Availability ─────────────────────────────────


def tor_binary() -> str | None:
    return shutil.which("tor")


def is_installed() -> bool:
    return tor_binary() is not None


def install_hint() -> str:
    return "brew install tor"


def data_dir() -> Path:
    return paths.state_dir() / "tor"


def torrc_path() -> Path:
    return data_dir() / "torrc"


def _cookie_path() -> Path:
    return data_dir() / "control_auth_cookie"


def _pid_path() -> Path:
    return data_dir() / "tor.pid"


# ── Configuration ────────────────────────────────


def build_torrc() -> str:
    """
    Render our torrc.

    Deliberately minimal. Tor's defaults are the product of far more scrutiny
    than anything invented here, so this sets only what the app needs: where to
    listen, where to keep state, and how to authenticate on the control port.
    """
    directory = data_dir()
    return f"""# Generated by VPN Agent. Edits are overwritten when Tor is started.
#
# Ports are 9250/9251 rather than Tor's usual 9050/9051 so this instance can
# coexist with a system Tor or with Tor Browser (which uses 9150).

SocksPort {SOCKS_PORT}
ControlPort {CONTROL_PORT}

DataDirectory {directory}
CookieAuthentication 1
CookieAuthFile {_cookie_path()}

# Never act as a relay or exit — this is a client only.
ClientOnly 1
ExitRelay 0

# Keep the log with the data rather than in a system location.
Log notice file {directory / "tor.log"}
"""


def write_torrc() -> Path:
    directory = paths.ensure_private_dir(data_dir())
    # Tor refuses to start if its DataDirectory is group- or world-readable.
    os.chmod(directory, 0o700)
    path = torrc_path()
    path.write_text(build_torrc(), encoding="utf-8")
    path.chmod(0o600)
    return path


# ── Lifecycle ────────────────────────────────────


def _port_is_open(port: int, host: str = "127.0.0.1", timeout: float = 0.4) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def is_running() -> bool:
    """True if something is answering on our SOCKS port."""
    return _port_is_open(SOCKS_PORT)


def start(timeout: float = STARTUP_TIMEOUT) -> tuple[bool, str]:
    """
    Start Tor and wait until it has finished bootstrapping.

    Returning as soon as the process starts would be a lie: Tor listens on the
    SOCKS port well before it has built a circuit, so an immediate request fails
    with a confusing SOCKS error. The log is watched for "Bootstrapped 100%"
    instead.
    """
    if not is_installed():
        return False, f"Tor is not installed. Install it with:  {install_hint()}"
    if is_running():
        return True, f"Tor is already listening on 127.0.0.1:{SOCKS_PORT}."

    write_torrc()
    log = data_dir() / "tor.log"
    if log.exists():
        log.unlink()

    try:
        process = subprocess.Popen(
            [tor_binary(), "-f", str(torrc_path())],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
    except OSError as exc:
        return False, f"Could not start Tor: {exc}"

    _pid_path().write_text(str(process.pid), encoding="utf-8")

    deadline = time.time() + timeout
    while time.time() < deadline:
        if process.poll() is not None:
            return False, f"Tor exited immediately.\n{_tail_log()}"
        if log.exists() and "Bootstrapped 100%" in log.read_text(errors="replace"):
            return True, f"Tor is up on 127.0.0.1:{SOCKS_PORT}."
        time.sleep(0.5)

    return False, (
        f"Tor did not finish bootstrapping within {int(timeout)}s. It may still "
        f"come up — some networks throttle or block Tor.\n{_tail_log()}"
    )


def stop() -> tuple[bool, str]:
    """Stop the Tor we started. Leaves a system Tor alone."""
    path = _pid_path()
    if not path.exists():
        if is_running():
            return False, (
                f"Something is listening on {SOCKS_PORT} but this app did not start "
                "it, so it will not be stopped."
            )
        return True, "Tor was not running."

    try:
        pid = int(path.read_text().strip())
    except (OSError, ValueError):
        path.unlink(missing_ok=True)
        return False, "The recorded Tor process id was unreadable."

    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        path.unlink(missing_ok=True)
        return True, "Tor had already stopped."
    except PermissionError:
        return False, f"Not permitted to stop process {pid}."

    deadline = time.time() + SHUTDOWN_TIMEOUT
    while time.time() < deadline:
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            path.unlink(missing_ok=True)
            return True, "Tor stopped."
        time.sleep(0.3)

    return False, f"Tor (pid {pid}) did not stop within {SHUTDOWN_TIMEOUT}s."


def _tail_log(lines: int = 8) -> str:
    log = data_dir() / "tor.log"
    if not log.exists():
        return "(no Tor log was written)"
    tail = log.read_text(errors="replace").strip().splitlines()[-lines:]
    return "\n".join(f"  {line}" for line in tail)


def bootstrap_progress() -> str:
    """The most recent bootstrap line, for showing progress while starting."""
    log = data_dir() / "tor.log"
    if not log.exists():
        return ""
    for line in reversed(log.read_text(errors="replace").splitlines()):
        if "Bootstrapped" in line:
            return line.split("]", 1)[-1].strip()
    return ""


# ── Using it ─────────────────────────────────────


def hop() -> ProxyHop:
    """This Tor instance as a chain hop."""
    return ProxyHop(kind=SOCKS5, host="127.0.0.1", port=SOCKS_PORT, label="Tor")


def check() -> tuple[bool, str]:
    """
    Ask the Tor Project whether we are really coming from a Tor exit.

    Checking rather than assuming matters: a SOCKS proxy that is reachable is
    not proof it is Tor, and "I configured it" is not the same as "it works".
    """
    if not is_running():
        return False, "Tor is not running."
    try:
        body = http_get_through([hop()], CHECK_HOST, "/api/ip", port=443, tls=True)
    except (SocksError, OSError) as exc:
        return False, f"Could not reach {CHECK_HOST} through Tor: {exc}"

    if '"IsTor":true' in body.replace(" ", ""):
        exit_ip = ""
        if '"IP":"' in body:
            exit_ip = body.split('"IP":"', 1)[1].split('"', 1)[0]
        return True, f"Confirmed: traffic is exiting through Tor{f' at {exit_ip}' if exit_ip else ''}."
    return False, f"{CHECK_HOST} says this traffic is NOT coming from Tor."


def new_identity() -> tuple[bool, str]:
    """
    Ask Tor for fresh circuits (the NEWNYM signal).

    This changes the exit you appear to come from. It does not clear anything
    the far end already knows about you — cookies, a login, a browser
    fingerprint — so it is not a way to become a different person mid-session.
    """
    if not is_running():
        return False, "Tor is not running."

    cookie = _cookie_path()
    if not cookie.exists():
        return False, "Tor's control cookie is missing; cannot authenticate."

    try:
        with socket.create_connection(("127.0.0.1", CONTROL_PORT), timeout=5) as control:
            control.sendall(b"AUTHENTICATE " + cookie.read_bytes().hex().encode() + b"\r\n")
            if not control.recv(256).startswith(b"250"):
                return False, "Tor rejected the control-port authentication."
            control.sendall(b"SIGNAL NEWNYM\r\n")
            if not control.recv(256).startswith(b"250"):
                return False, "Tor refused the NEWNYM signal."
    except OSError as exc:
        return False, f"Could not reach Tor's control port: {exc}"

    return True, "New Tor circuit requested — your exit address should change."
