#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# NOT the everyday script. Use scripts/install_app.sh instead — that installs a
# launcher that runs this project's code live, so edits apply on next launch
# with no rebuild.
#
# This one FREEZES the code into the bundle: running it replaces the live app in
# /Applications with a snapshot, and you are back to re-running a build after
# every edit. Keep it only for producing a self-contained bundle to hand to
# another machine (no project folder or .venv required there).
# ─────────────────────────────────────────────────────────────────────────────
#
# Build & install "Sentinel Fork.app" — a self-contained macOS application bundle
# produced by PyInstaller (bundles its own Python + every dependency). Unlike a
# dev checkout, the app does NOT need the project's .venv or even the project
# folder once installed.
#
#   ./scripts/build_app.sh            # build + install to /Applications
#   ./scripts/build_app.sh --no-install   # build only (dist/Sentinel Fork.app)
#
# IMPORTANT: the bundle freezes the CODE at build time. After editing main.py (or
# anything else), re-run this script to refresh the installed app.
#
# Writable state (SQLite DB, saved chats, logs, editable config, API keys) lives
# in  ~/Library/Application Support/Sentinel Fork/  — seeded on first launch and
# preserved across rebuilds. Put API keys in that folder's .env file.
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_NAME="Sentinel Fork"
APP_BUNDLE="${APP_NAME}.app"
DIST_APP="${PROJECT_ROOT}/dist/${APP_BUNDLE}"
INSTALLED="/Applications/${APP_BUNDLE}"
PY="${PROJECT_ROOT}/.venv/bin/python"

cd "$PROJECT_ROOT"

echo "▸ Building ${APP_BUNDLE} with PyInstaller (this takes ~1 min)…"
mkdir -p "${PROJECT_ROOT}/dist"
# Keep Spotlight out of the build output, so the freshly built copy in dist/
# never shows up as a second "Sentinel Fork" alongside the installed one.
touch "${PROJECT_ROOT}/dist/.metadata_never_index"
"$PY" -m PyInstaller --noconfirm --clean SentinelAI.spec

if [ "${1:-}" = "--no-install" ]; then
    echo "✓ Built: ${DIST_APP}"
    exit 0
fi

echo "▸ Installing to ${INSTALLED}…"
# Stop any running instance so Launch Services picks up the new binary.
pkill -f "${APP_BUNDLE}/Contents/MacOS" 2>/dev/null || true
sleep 1
rm -rf "$INSTALLED"
cp -R "$DIST_APP" "$INSTALLED"

# Clear any extended attributes and ad-hoc sign so Gatekeeper allows the local app.
xattr -cr "$INSTALLED" 2>/dev/null || true
codesign --force --deep --sign - "$INSTALLED"

# Register with Launch Services so it shows up in Spotlight / Launchpad.
LSREG="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
"$LSREG" -f "$INSTALLED"
# ...and drop the build copy from Launch Services, so Spotlight/Launchpad only
# ever offer the installed /Applications one.
"$LSREG" -u "$DIST_APP" 2>/dev/null || true

# Deregistering alone does not stick once Spotlight has indexed the bundle (it
# keeps returning for "Sentinel", and launching THAT copy silently runs a
# build that drifts out of date). The build output is byte-identical to what we
# just installed and is regenerated by the next build, so remove it outright —
# that guarantees exactly one "Sentinel" app exists on disk.
rm -rf "$DIST_APP"

echo ""
echo "✓ Installed: ${INSTALLED}"
echo "  Launch it from Spotlight, Launchpad, or /Applications."
echo "  API keys: ~/Library/Application Support/${APP_NAME}/.env"
